/**
 * Generated by: pnpm db:types (from repo root, requires `supabase link`)
 * Placeholder until linked project types are generated.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          phone: string | null;
          name: string | null;
          email: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          phone?: string | null;
          name?: string | null;
          email?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          phone?: string | null;
          name?: string | null;
          email?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          user_id: string;
          current_role: string | null;
          experience_years: number | null;
          employer: string | null;
          skills: string[];
          target_roles: string[];
          work_preference: string | null;
          career_goal: string | null;
          projects: Json;
          cv_yaml: string | null;
          embedding: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          current_role?: string | null;
          experience_years?: number | null;
          employer?: string | null;
          skills?: string[];
          target_roles?: string[];
          work_preference?: string | null;
          career_goal?: string | null;
          projects?: Json;
          cv_yaml?: string | null;
          embedding?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          current_role?: string | null;
          experience_years?: number | null;
          employer?: string | null;
          skills?: string[];
          target_roles?: string[];
          work_preference?: string | null;
          career_goal?: string | null;
          projects?: Json;
          cv_yaml?: string | null;
          embedding?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      jobs: {
        Row: {
          id: string;
          source_name: string;
          external_id: string;
          title: string;
          company: string;
          location: string | null;
          url: string;
          description: string | null;
          posted_at: string | null;
          fetched_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          source_name: string;
          external_id: string;
          title: string;
          company: string;
          location?: string | null;
          url: string;
          description?: string | null;
          posted_at?: string | null;
          fetched_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          source_name?: string;
          external_id?: string;
          title?: string;
          company?: string;
          location?: string | null;
          url?: string;
          description?: string | null;
          posted_at?: string | null;
          fetched_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      applications: {
        Row: {
          id: string;
          user_id: string;
          job_id: string;
          match_score: number;
          match_reasons: string[];
          cv_version_url: string | null;
          cover_letter: string | null;
          status: string;
          notified_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          job_id: string;
          match_score: number;
          match_reasons?: string[];
          cv_version_url?: string | null;
          cover_letter?: string | null;
          status?: string;
          notified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          job_id?: string;
          match_score?: number;
          match_reasons?: string[];
          cv_version_url?: string | null;
          cover_letter?: string | null;
          status?: string;
          notified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "applications_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "applications_job_id_fkey";
            columns: ["job_id"];
            isOneToOne: false;
            referencedRelation: "jobs";
            referencedColumns: ["id"];
          },
        ];
      };
      sources: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          type: string;
          config: Json;
          is_active: boolean;
          last_polled_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          type: string;
          config?: Json;
          is_active?: boolean;
          last_polled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          type?: string;
          config?: Json;
          is_active?: boolean;
          last_polled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "sources_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      cv_uploads: {
        Row: {
          id: string;
          user_id: string;
          original_filename: string;
          storage_path: string;
          status: string;
          error_message: string | null;
          uploaded_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          original_filename: string;
          storage_path: string;
          status?: string;
          error_message?: string | null;
          uploaded_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          original_filename?: string;
          storage_path?: string;
          status?: string;
          error_message?: string | null;
          uploaded_at?: string;
        };
        Relationships: [];
      };
      parsed_cv_data: {
        Row: {
          id: string;
          upload_id: string;
          structured_json: Json;
          rendercv_yaml: string | null;
          model_used: string | null;
          parsed_at: string;
        };
        Insert: {
          id?: string;
          upload_id: string;
          structured_json: Json;
          rendercv_yaml?: string | null;
          model_used?: string | null;
          parsed_at?: string;
        };
        Update: {
          id?: string;
          upload_id?: string;
          structured_json?: Json;
          rendercv_yaml?: string | null;
          model_used?: string | null;
          parsed_at?: string;
        };
        Relationships: [];
      };
      render_jobs: {
        Row: {
          id: string;
          upload_id: string;
          application_id: string | null;
          status: string;
          output_storage_path: string | null;
          error_message: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          upload_id: string;
          application_id?: string | null;
          status?: string;
          output_storage_path?: string | null;
          error_message?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          upload_id?: string;
          application_id?: string | null;
          status?: string;
          output_storage_path?: string | null;
          error_message?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
